### ISSUE TITLE
Optional arguments

### ISSUE THREAD

**Issue by fay-askari72** [mauriciolp/inter-rel-net#4]
Hi, 

Will you please explain what does  '-s' (evaluation over sequences average) does in the code?

Thank you

**Comment by mauriciolp** [comment]
Hello,

Before implementing the final LSTM solution, I tried average pooling the scores over a sequence in a temporal sliding window fashion. The option '-s' (-seqs-eval) is related to that.
None of my results in the paper actually uses this option.
However it might be useful as a baseline result before trying the LSTM variations.

Cheers.
