### ISSUE TITLE
About predictions and files

### ISSUE THREAD

**Issue by ylabminji** [mauriciolp/inter-rel-net#6]
About predictions and files

First of all, thank you very much for sharing this good source code on github.

After downloading the clone from github, I have a question and write a few questions.

From my understanding I think run_protocol.py is to train a specific dataset for action recognition. Is this correct? If not, I'm curious to know in detail what the file is for.

And I want to predict what kind of action I will do with my video data. What should I do?
After extracting Skeleton Data using Openpose from image data,
Is it possible to use predict_rn.py file? I'm not sure which py file to do.

**Comment by mauriciolp** [comment]
Hi @ylabminji , thanks for the interest.

You are right, _run_protocol.py_ is for training and evaluation on a specific dataset.

I haven't prepared a stand-alone script for classifying a single video data.
But in the files _predict_rn.py_ and _predict_rn_temp.py_ there are auxiliary functions for generating predictions for the validation split of a specific dataset. 
Check _predict_fused_temp_rn()_ in _predict_temp_rn.py_ for a good example.

To classify an unlabeled video or batch of videos, it would be necessary to write a new script.
